//
//  UseKeyChainInteractor.swift
//  Personal
//
//  Created by app on 2021/12/03.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UseKeyChainBusinessLogic
{
    func doSomething(request: UseKeyChain.Something.Request)
}

protocol UseKeyChainDataStore
{
    //var name: String { get set }
}

class UseKeyChainInteractor: UseKeyChainBusinessLogic, UseKeyChainDataStore
{
    var presenter: UseKeyChainPresentationLogic?
    var worker: UseKeyChainWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: UseKeyChain.Something.Request)
    {
        worker = UseKeyChainWorker()
        worker?.doSomeWork()
        
        let response = UseKeyChain.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
