//
//  NoticeBoardPresenter.swift
//  Personal
//
//  Created by 으정이 on 2021/10/09.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoticeBoardPresentationLogic
{
  func presentSomething(response: NoticeBoard.Something.Response)
}

class NoticeBoardPresenter: NoticeBoardPresentationLogic
{
  weak var viewController: NoticeBoardDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NoticeBoard.Something.Response)
  {
    let viewModel = NoticeBoard.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
