//
//  LocalizationPresenter.swift
//  Personal
//
//  Created by 으정이 on 2021/10/31.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocalizationPresentationLogic
{
}

class LocalizationPresenter: LocalizationPresentationLogic
{
  weak var viewController: LocalizationDisplayLogic?
  
  // MARK: Do something
  
}
