//
//  LocalizationRouter.swift
//  Personal
//
//  Created by 으정이 on 2021/10/31.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LocalizationRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LocalizationDataPassing
{
  var dataStore: LocalizationDataStore? { get }
}

class LocalizationRouter: NSObject, LocalizationRoutingLogic, LocalizationDataPassing
{
  weak var viewController: LocalizationViewController?
  var dataStore: LocalizationDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: LocalizationViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: LocalizationDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
